---
include:
  - ../storage/docker-compose.yml
services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: 
      - ../../env/shared/.env
      - ../../env/outline/.env
    expose: ['3000']
    volumes: [storage-data:/var/lib/outline/data]
    depends_on: [postgres, redis]

volumes:
  storage-data:
