---
include:
  - ../storage/docker-compose.yml
services:
  outline:
    container_name: bmmit-outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: 
      - ../../env/shared/.env
      - ../../env/outline/.env
    expose: ['3000']
    volumes: [../../data/outline:/var/lib/outline/data]
    depends_on: [postgres, redis]
  cloudflare_outline:
    container_name: bmmit-cloudflare-outline
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file: ../../env/outline/.env
    restart: always
volumes:
  storage-data:
